set(VCPKG_ENV_PASSTHROUGH_UNTRACKED STM32CLT_PATH PATH)

set(VCPKG_TARGET_ARCHITECTURE Generic)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)
set(VCPKG_CMAKE_SYSTEM_NAME arm-none-eabi)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../cmake/gcc-arm-none-eabi.cmake")
